const { contextBridge, ipcRenderer } = require('electron');
const inv = (ch, ...a) => ipcRenderer.invoke(ch, ...a);

contextBridge.exposeInMainWorld('api', {
  db: {
    exportFile: ()          => inv('db:exportFile'),
    importFileMerge: ()     => inv('db:importFileMerge'),
  },
  folder: {
    getAll:  ()            => inv('folder:getAll'),
    create:  (n,m,c)       => inv('folder:create', n,m,c),
    update:  (id,n,m,c)    => inv('folder:update', id,n,m,c),
    delete:  (id)          => inv('folder:delete', id),
  },
  project: {
    getAll:  (fid)         => inv('project:getAll', fid),
    get:     (id)          => inv('project:get', id),
    create:  (data)        => inv('project:create', data),
    update:  (id,data)     => inv('project:update', id, data),
    delete:  (id)          => inv('project:delete', id),
    getDesc: (pid)         => inv('project:getDesc', pid),
    addDesc: (pid,n,t)     => inv('project:addDesc', pid,n,t),
    updDesc: (id,n,t)      => inv('project:updDesc', id,n,t),
    delDesc: (id)          => inv('project:delDesc', id),
    getTags: (pid)        => inv('project:getTags', pid),
    setTags: (pid,tags)   => inv('project:setTags', pid,tags),
    addTag: (pid,tid)     => inv('project:addTag', pid,tid),
    removeTag: (pid,tid)  => inv('project:removeTag', pid,tid),
    getAllUsedTags: (pid)  => inv('project:getAllUsedTags', pid),
  },
  category: {
    getAll:  (pid)         => inv('category:getAll', pid),
    create:  (pid,n,c)     => inv('category:create', pid,n,c),
    update:  (id,n,c)      => inv('category:update', id,n,c),
    delete:  (id)          => inv('category:delete', id),
  },
  template: {
    getAll:  (cid)         => inv('template:getAll', cid),
    create:  (cid,d,t)     => inv('template:create', cid,d,t),
    update:  (id,d,t)      => inv('template:update', id,d,t),
    delete:  (id)          => inv('template:delete', id),
  },
  object: {
    getAll:  (cid)         => inv('object:getAll', cid),
    get:     (id)          => inv('object:get', id),
    create:  (pid,cid,n,c) => inv('object:create', pid,cid,n,c),
    update:  (id,n,c)      => inv('object:update', id,n,c),
    updateNote: (id,note)  => inv('object:updateNote', id,note),
    delete:  (id)          => inv('object:delete', id),
    getAttrs:(oid)         => inv('object:getAttrs', oid),
    upsertAttr:(oid,tid,v) => inv('object:upsertAttr', oid,tid,v),
    getCategoryAttrs:(cid) => inv('object:getCategoryAttrs', cid),
    getTags: (oid)         => inv('object:getTags', oid),
    setTags: (oid,tags)    => inv('object:setTags', oid,tags),
    addTag: (oid,tid)      => inv('object:addTag', oid,tid),
    removeTag: (oid,tid)   => inv('object:removeTag', oid,tid),
  },
  timeline: {
    getAll:  (pid)        => inv('timeline:getAll', pid),
    create:  (pid,n,c)    => inv('timeline:create', pid,n,c),
    update:  (id,n,c)     => inv('timeline:update', id,n,c),
    delete:  (id)         => inv('timeline:delete', id),
    getOrCreateDate: (d,m,y,hh,mm) => inv('timeline:getOrCreateDate', d,m,y,hh,mm),
    getEvents: (tlid)     => inv('timeline:getEvents', tlid),
    createEvent: (tlid,n,s,e,c,story) => inv('timeline:createEvent', tlid,n,s,e,c,story),
    updateEvent: (id,n,s,e,c,story)  => inv('timeline:updateEvent', id,n,s,e,c,story),
    updateEventStory: (id,story) => inv('timeline:updateEventStory', id,story),
    deleteEvent: (id)     => inv('timeline:deleteEvent', id),
    getEventTags: (eid)   => inv('timeline:getEventTags', eid),
    setEventTags: (eid,tags) => inv('timeline:setEventTags', eid,tags),
    addEventTag: (eid,tid) => inv('timeline:addEventTag', eid,tid),
    removeEventTag: (eid,tid) => inv('timeline:removeEventTag', eid,tid),
  },
  relation: {
    getTypes: ()          => inv('relation:getTypes'),
    createType: (n,c)     => inv('relation:createType', n,c),
    updateType: (id,n,c)  => inv('relation:updateType', id,n,c),
    deleteType: (id)      => inv('relation:deleteType', id),
    getOBOB: (pid)        => inv('relation:getOBOB', pid),
    createOBOB: (pid,tid,c,f,t) => inv('relation:createOBOB', pid,tid,c,f,t),
    deleteOBOB: (id)      => inv('relation:deleteOBOB', id),
    update: (id,tid,c)     => inv('relation:update', id,tid,c),
    getOBTL: (pid)        => inv('relation:getOBTL', pid),
    createOBTL: (pid,tid,c,f,t) => inv('relation:createOBTL', pid,tid,c,f,t),
    deleteOBTL: (id)      => inv('relation:deleteOBTL', id),
    getTLTL: (pid)        => inv('relation:getTLTL', pid),
    createTLTL: (pid,tid,c,f,t) => inv('relation:createTLTL', pid,tid,c,f,t),
    deleteTLTL: (id)      => inv('relation:deleteTLTL', id),
    getProjectObjects: (pid) => inv('relation:getProjectObjects', pid),
    getProjectEvents: (pid)  => inv('relation:getProjectEvents', pid),
  },
  map: {
    getAll: (pid)            => inv('map:getAll', pid),
    create: (pid,n,c)        => inv('map:create', pid,n,c),
    update: (id,n,c)         => inv('map:update', id,n,c),
    delete: (id)             => inv('map:delete', id),
    getAreas: (mid)          => inv('map:getAreas', mid),
    createArea: (mid,n,c)    => inv('map:createArea', mid,n,c),
    updateArea: (id,n,c)     => inv('map:updateArea', id,n,c),
    deleteArea: (id)         => inv('map:deleteArea', id),
    getPoints: (aid)         => inv('map:getPoints', aid),
    setPoints: (aid,points)  => inv('map:setPoints', aid, points),
  },
  hashtag: {
    getAll:  ()           => inv('hashtag:getAll'),
    create:  (n,c)        => inv('hashtag:create', n,c),
    update:  (id,n,c)     => inv('hashtag:update', id,n,c),
    delete:  (id)         => inv('hashtag:delete', id),
    getObjectsByTag: (tagId, projectId) => inv('hashtag:getObjectsByTag', tagId, projectId),
    getEventsByTag: (tagId, projectId)  => inv('hashtag:getEventsByTag', tagId, projectId),
  },
  color: {
    getAll:  ()            => inv('color:getAll'),
    add:     (code)        => inv('color:add', code),
    markUsed:(id)          => inv('color:markUsed', id),
    getRecent:()           => inv('color:getRecent'),
    delete:  (id)          => inv('color:delete', id),
  },
  search: {
    all:     (q)           => inv('search:all', q),
  },
  window: {
    minimize:       () => inv('window:minimize'),
    toggleMaximize: () => inv('window:toggleMaximize'),
    close:          () => inv('window:close'),
  },
});
